/* Demo data — static, no API calls. Mirrors FastAPI /triage response model. */
const D = {
  meta: {
    incidentRef: "INC-2026-0428-117",
    analyst: "S. Clark",
    analystRole: "OHS Consultant · ML Engineering Portfolio",
    submittedAt: "2026-04-28T09:42:11Z",
    pipelineVersion: "rag-triage-api v0.1.0",
    modelStack: "stuSterfc/ohs-severity-classifier · map_riddor · analyse_causes · find_patterns",
  },
  narrative: "On the morning of 26 April 2026 at approximately 07:50, a service user (SU-431, 78yo, mod. dementia, mobility-impaired) was being assisted from bed to a wheeled commode by a single care worker (CW-12) on the second floor of Beechfield Residential. The mobile hoist normally used had been removed for sling inspection the previous evening and was not yet returned; this was not flagged at the morning handover. The care worker performed an unaided pivot transfer. The service user's left foot caught on the bedframe, both fell to the carpeted floor. The service user sustained a suspected fractured left hip and was conveyed by ambulance to North Tyneside General. The care worker reported lower-back strain but did not require hospitalisation. The room had recently been re-arranged for a deep clean; bed brakes were engaged. CCTV in the corridor confirms the timeline. SU-431's care plan flags 'two-person transfer with hoist'. The shift leader was alerted at 07:58 and the duty manager at 08:05.",
  severityClasses: [
    { id: 0, name: "None",     band: "0 days" },
    { id: 1, name: "Minor",    band: "1–2 days" },
    { id: 2, name: "Moderate", band: "3–7 days" },
    { id: 3, name: "Severe",   band: "8–28 days" },
    { id: 4, name: "Major",    band: "29+ days" },
  ],
  severity_prediction: {
    probabilities: {
      "Major (29+ days)":    0.3924,
      "Severe (8-28 days)":  0.2993,
      "Moderate (3-7 days)": 0.1763,
      "Minor (1-2 days)":    0.0679,
      "None (0 days)":       0.0641,
    },
    predicted_class: 4,
    confidence: 0.3924,
    needlestick_flag: false,
    predicted_label: "Major (29+ days)",
    middle_severity_flag: false,
  },
  riddor_advisory: {
    potentially_applicable: [
      {
        category: "Over-7-day incapacitation (Regulation 4)",
        description: "An injury to a person at work causing incapacitation from routine work for more than seven consecutive days. The predicted incapacitation of Major (29+ days) suggests this threshold may be met — confirmation from a medical practitioner is required before any determination.",
        information_needed: [
          "Confirmation from a medical practitioner that the care assistant is incapacitated for more than seven consecutive days (excluding the day of the accident).",
        ],
        reporting_deadline: "Within 15 days of the accident.",
      },
      {
        category: "Specified injuries to workers (Regulation 5)",
        description: "Certain serious injuries to a person at work require immediate reporting. Lower back pain is not itself a specified injury, but may be symptomatic of one such as a vertebral fracture. No determination is possible without further medical information.",
        information_needed: [
          "Confirmation from a registered medical practitioner whether the injury involves a bone fracture.",
          "Information regarding whether the care assistant suffered loss of consciousness or any other specified injury listed under Regulation 5.",
        ],
        reporting_deadline: "Immediately (reportable without delay), if confirmed.",
      },
      {
        category: "Non-fatal injuries to non-workers (Regulation 5)",
        description: "An injury to a person not at work resulting from a work-related accident may be reportable if that person is taken to hospital for treatment. The resident became unsteady during the transfer — whether a reportable injury occurred requires confirmation.",
        information_needed: [
          "Confirmation of whether the resident was injured as a result of the incident.",
          "If injured, confirmation of whether the resident was taken from the site to a hospital for treatment.",
        ],
        reporting_deadline: "Immediately (reportable without delay), if confirmed.",
      },
      {
        category: "Record-keeping obligation — 3-day incapacitation (Regulation 12(1)(c))",
        description: "A record must be kept of any work-related injury incapacitating a person at work for more than three consecutive days. Given the predicted incapacitation period, this obligation is likely triggered. This is a record-keeping obligation only — not a report to HSE.",
        information_needed: [],
        reporting_deadline: "Not a reporting deadline — record must be kept for at least three years.",
      },
    ],
    follow_up_questions: [
      "What is the specific medical diagnosis for the care assistant's lower back pain? Does it involve a bone fracture or any other injury specified under Regulation 5?",
      "Has a registered medical practitioner confirmed the incapacitation period for the care assistant? If so, what is the confirmed period for routine work (excluding the day of the accident)?",
      "Was the resident injured during the incident?",
      "If the resident was injured, were they taken from the site of the accident to a hospital for treatment for that injury?",
      "Was the incident on hospital premises, and if so, did the resident suffer a 'specified injury' as defined by RIDDOR?",
      "What was the exact state of the floor in the area where the incident occurred, and had any wet floor signs been put in place?",
      "Were there any other witnesses to the incident?",
      "What was the care assistant's routine work, and are they genuinely unable to perform it due to the injury?",
    ],
    disclaimer: "This is a conditional advisory only. A competent person must make the final RIDDOR determination when full information is available. This output does not constitute a legal determination.",
  },
  causal_analysis: {
    identified_causes: [
      {
        cause_type: "Premises",
        description: "Recently mopped and slightly wet floor creating a slip or instability hazard during the resident transfer.",
        hsg220_section: "HSG220 Ch.6 (pp.32–34), Ch.3 (pp.17–21), Ch.8 (pp.39–44)",
        mitigation_actions: [
          "Use slip-resistant flooring where surface contamination cannot be controlled.",
          "Prevent floors from getting contaminated by water and other fluids.",
          "Design tasks to minimise spillages.",
          "Control contamination through containing and effectively cleaning spillages.",
          "Establish procedures for quickly and effectively dealing with spillages.",
          "Choose effective cleaning methods, avoiding additional slip or trip risks.",
          "Restrict access to smooth floors left damp by mopping until dry.",
          "Implement adequate segregation during traditional mopping until the floor is dry.",
          "Provide staff with suitable, slip-resistant footwear where slip risks exist.",
          "Foster a 'see it, sort it' attitude for immediate spill clean-up.",
          "Include environmental slip risk factors in care plans for high-risk residents.",
        ],
      },
      {
        cause_type: "Practices",
        description: "Unsafe or inadequate moving and handling practice during transfer, especially when the resident became unsteady.",
        hsg220_section: "HSG220 Ch.3 (pp.17–21), Ch.2 (pp.14–16), Ch.11 (pp.52–55)",
        mitigation_actions: [
          "Assess moving and handling risks, ensuring competent staff identify issues.",
          "Seek specialist advice for residents with specific moving and handling needs.",
          "Consider staff competence and training for all moving and handling tasks.",
          "Consider the environment, including flooring, lighting, and space restrictions.",
          "Consider specific resident needs as part of the care planning process.",
          "Communicate moving and handling information to staff, keeping it accessible.",
          "Document resident's ability to support weight and relevant factors in care plans.",
          "Specify the number of staff required for different types of transfers.",
          "Train staff to manage changing resident needs, abilities, or agitation during transfers.",
          "Use moving and handling equipment only after assessment and with care plans.",
          "Follow manufacturer's instructions for all moving and handling equipment.",
          "Review person-centred plans periodically and when resident needs change.",
          "Ensure staff are competent in safe moving and handling techniques.",
          "Provide sufficient and appropriate moving and handling equipment.",
          "Never leave vulnerable persons unattended in a hoist or prone to falling.",
        ],
      },
      {
        cause_type: "People",
        description: "Care worker's manual handling training or technique may have been insufficient to manage the transfer safely without the hoist.",
        hsg220_section: "HSG220 Ch.3 (pp.17–21), Ch.2 (pp.14–16), Ch.1 (pp.8–13)",
        mitigation_actions: [
          "Ensure a trained, skilled, and competent workforce.",
          "Provide clear instructions, information, and adequate training for employees.",
          "Ensure all employees know how to work safely and without health risks.",
          "Identify training needs to ensure staff competence in moving and handling.",
          "Include practical instructions, demonstrations, and practice in manual handling training.",
          "Monitor staff for safe practices, identifying further instruction or supervision needs.",
          "Review training when tasks, equipment, or responsibilities change.",
          "Check that staff follow established safety arrangements.",
        ],
      },
      {
        cause_type: "Equipment",
        description: "Mobile hoist removed for sling inspection the previous evening and not returned before morning transfers commenced. Shortfall not visible at handover.",
        hsg220_section: "HSG220 Ch.5 (pp.28–31), LOLER 1998 Reg.9",
        mitigation_actions: [
          "Implement a logged check-in / check-out procedure for safety-critical equipment.",
          "Add equipment status to the morning handover template — mandatory confirmation.",
          "Provision a back-up hoist on each floor so a withdrawn unit never leaves a floor without cover.",
          "Ensure LOLER inspection records are current and accessible to staff.",
          "Define an escalation pathway for missing safety-critical equipment at handover.",
        ],
      },
    ],
    disclaimer: "These are directions for investigation only. Determination of root cause requires full investigation by a competent person.",
  },
  pattern_analysis: {
    similar_incidents: [
      { narrative_excerpt: "Assisting confused resident who was not cooperative with care. During transfer of resident from wheelchair to toileting felt lower back pain that radiated down her left leg.", severity_outcome: 4 },
      { narrative_excerpt: "Assisting aide in transferring resident from wheelchair to bed. Resident started to slip off the bed; they then tried to lift resident to the bed when pain in lower back occurred.", severity_outcome: 2 },
      { narrative_excerpt: "Helping a resident back in their wheelchair. Resident was attempting to put themselves on the ground. Employee heard a pop and sudden pain in lower back. Body mechanics — repositioning.", severity_outcome: 1 },
      { narrative_excerpt: "Assisting with resident transfer. Felt a sharp pain in low left side of back while pulling resident away from the dining room table in their wheelchair.", severity_outcome: 2 },
      { narrative_excerpt: "Injured employee was assisting a patient from the wheelchair to the bed. They had to twist to not injure the patient while getting the patient into bed. Lower back pain.", severity_outcome: 0 },
      { narrative_excerpt: "The employee was assisting transferring the resident from the bed to the wheelchair. Employee felt low back pain while transferring the resident.", severity_outcome: 2 },
      { narrative_excerpt: "While assisting a resident to the bed from the wheelchair felt a pain in lower back.", severity_outcome: 4 },
      { narrative_excerpt: "Injured employee was transferring a resident from her bed to her wheelchair when the resident almost fell. After getting the resident into her wheelchair she felt pain in her lower back.", severity_outcome: 0 },
      { narrative_excerpt: "Employee was assisting the resident to get up from the wheelchair and felt a pain in her lower back.", severity_outcome: 2 },
      { narrative_excerpt: "Associate was assisting resident with transfer into bed and upon bending to assist resident felt pain in her lower back.", severity_outcome: 3 },
    ],
    severity_distribution: { "0": 12, "1": 10, "2": 18, "3": 34, "4": 26 },
    injury_mechanism: "Not extractable from current dataset — OSHA H&C records contain narrative text and severity labels only. Activity patterns are visible in the similar incidents above.",
  },
  domain_disclaimer: "DOMAIN CONSTRAINT: This system was trained exclusively on OSHA Health and Social Care sector data from care home settings. It has not been validated outside this domain. All outputs are decision-support tools only — not compliance determinations.",
};